# Generated by Django 5.1.2 on 2024-10-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monie', '0002_alter_category_options_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
